# Generated by Django 4.2.5 on 2023-10-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sondage',
            name='titre',
            field=models.CharField(default='titre par defaut', max_length=50),
        ),
    ]
