# Generated by Django 4.2.5 on 2023-10-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sondage_app', '0002_sondage_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondage',
            name='reponse',
        ),
        migrations.AddField(
            model_name='reponse',
            name='id_sondage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sondage_app.sondage'),
        ),
    ]
