# Generated by Django 4.2.5 on 2023-10-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondage_app', '0003_remove_sondage_reponse_reponse_id_sondage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sondage',
            name='question',
        ),
    ]
