# Generated by Django 4.2.5 on 2023-10-01 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondage_app', '0004_remove_sondage_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sondage',
            old_name='client_id',
            new_name='client',
        ),
    ]
