# Generated by Django 4.2.5 on 2023-10-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondage_app', '0005_rename_client_id_sondage_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='identificateur_sondage',
            new_name='sondage_associer',
        ),
    ]
