# Generated by Django 4.2.5 on 2023-10-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondage_app', '0006_rename_identificateur_sondage_question_sondage_associer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='id_sondage',
            new_name='sondage',
        ),
    ]
