# Generated by Django 4.2.5 on 2023-10-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondage_app', '0007_rename_id_sondage_reponse_sondage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='id_client',
            new_name='client',
        ),
    ]
